# Generated by Django 2.2.16 on 2022-04-23 15:44

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20220423_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_comm',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='posts.Comment', verbose_name='Родительская категория'),
        ),
    ]
